### ISSUE TITLE
single store with Multi app

### ISSUE THREAD

**Issue by BhaskaranR** [angular-redux/ng-redux#128] opened 2017-04-17 14:24 UTC
This is more a question than issue. we have a angular multiple app running in a liferay portal. I would want to create a single store that would be share across multiple angular apps.  How can I use ngredux to a achieve this?
thanks.

**Comment by floriangosse** [comment] 2017-11-27 14:46
I think you're looking for a feature which will be implemented for version 4.0.0:
> implement provideStore functionality (...) &ndash; #164

**Comment by AntJanus** [comment] 2017-11-27 19:23
The development on this has definitely stalled a bit (if only I had infinite time on my hands!). But here are a few things you can do:

1. if you're running multiple angular applications on a single page, create a separate AngularJS module that gets injected into all the apps
2. create a Redux store and at runtime, inject it into `ng-redux` using an enhancer. As long as all your redux middleware and reducers are available together immediately, this should be pretty straightforward.

I use the second approach in an AngularJS/Angular app that shares state. Basically it looks like this:

```js
const myStore = createStore(combineReducers({ foo, bar }), initialState, applyMiddleware(thunkMiddleware);

export function sharedReduxEnhancer(createStore) {
  return () => {
     return myStore;
  };
};
```

And then you use the `sharedReduxEnhancer` in your Redux setup. What that will do is basically throw away `ng-redux`'s store, and replace it with the shared one. So far, the only bugs that come up are related to trying to add special middleware or functionality only in the AngularJS side or only in the Angular side; however, if you can share behavior between your apps, this shouldn't be a problem.

**Comment by AntJanus** [comment] 2018-01-08 16:57
I'm gonna close this since it's a duplicate of #19. It's slated for 4.0.0 release.

**Closed by AntJanus** 2018-01-08 16:57 UTC
